name: CodeRabbit AI Review

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run CodeRabbit Review
        uses: coderabbitai/pr-agent@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
